FROM ubuntu:22.04

LABEL org.opencontainers.image.authors="Fernando Barros, <fernando.barros@ee.ufcg.edu.br>"

RUN apt update 
RUN apt install -y inetutils-ping curl nano net-tools iproute2 apache2 \
		ufw openssh-server
